### ISSUE TITLE
remove code which is not future-proof

### ISSUE THREAD

**Issue by ghost** [coq/coq-bench#31] opened 2017-04-20 13:40 UTC
[This chunk](https://github.com/coq/coq-bench/blob/510246764c1e3cd9e5f983c72f12b34c5b9a226c/two_points_on_the_same_branch.sh#L214-L228) is not future-proof.

Once a new version of Coq is released, the code will break.

We need to find a better way to achieve the same goal.

**Comment by ejgallego** [comment] 2018-10-23 11:44
Basically a duplicate of #30.

**Closed as completed by ejgallego** 2018-10-23 11:44 UTC
Labels: kind: bug
