### ISSUE TITLE
Measure (also) compilation at the level of individual files.

### ISSUE THREAD

**Issue by ghost** [coq/coq-bench#33] opened 2017-06-02 13:27 UTC
It would be useful if the benchmarking job was able to provide deeper insight concerning changes of compilation times.
- at the level of individual files
- at the level of individual theorems.

**Comment by JasonGross** [comment] 2017-06-02 23:57
Is opam configurable enough that you can get the logs of running `make`?

For developments that use `coq_makefile` (or otherwise provide access to the equivalent of `TIMED=1`), you can do this:
1. run `make` with `TIMED=1` and `tee` the output to some file, say, `before.log` for the old times and `after.log` for the new times
2. clone [coq-scripts](https://github.com/JasonGross/coq-scripts)
3. run `python /path/to/coq-scripts/timing/make-both-time-files.py after.log before.log diff.log`
4. run `cat diff.log`

This will give you a table of the file-level diff.  (Currently it just does absolute times; do you want me to add a column for percentages?)

This, for example, should work with fiat-crypto, fiat-parsers, bedrock-*, and HoTT, at least.

At the level of individual files, we have [a target in HoTT that makes `*.timing` files based on `coqc -time`](https://github.com/HoTT/HoTT/blob/master/Makefile.am#L230), though I'm not sure if that's helpful.

**Comment by ejgallego** [comment] 2019-01-23 12:54
Duplicate of #18

**Closed as completed by ejgallego** 2019-01-23 12:55 UTC
